# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "LICENSE.txt", "_stage"]
highlighter: 'rouge' 

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

imagerepository: https://einkoffervollerreisen.blob.core.windows.net/

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Wir heiraten!
subtitle: Liza & Robert heiraten
author :
  name : Robert Mühsig
  email : contact@codeinside.eu
  github : robertmuehsig

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : https://wir-heiraten.einkoffervollerreisen.de
production_url_theme : https://wir-heiraten.einkoffervollerreisen.de/travelogue

github_repo_url: https://github.com/robertmuehsig/wedding/

